--- !ditz.rubyforge.org,2008-03-06/project 
name: mangos2
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: mangos2
- !ditz.rubyforge.org,2008-03-06/component 
  name: Tools
- !ditz.rubyforge.org,2008-03-06/component 
  name: Documentation
- !ditz.rubyforge.org,2008-03-06/component 
  name: Build
- !ditz.rubyforge.org,2008-03-06/component 
  name: Shared library
- !ditz.rubyforge.org,2008-03-06/component 
  name: Authentication and realm list server
- !ditz.rubyforge.org,2008-03-06/component 
  name: World server
- !ditz.rubyforge.org,2008-03-06/component 
  name: Voice chat server
- !ditz.rubyforge.org,2008-03-06/component 
  name: Installation
releases: []

