DELETE FROM `protoitem` WHERE
-- Start items for all classes:
 `name` <> "Hearthstone"
-- Start armor for :
-- Start items for :
-- Start weapons for :
-- Miscellaneous items
AND `name` <> "Acolyte\'s Pants"
AND `name` <> "Acolyte\'s Robe"
AND `name` <> "Acolyte\'s Shirt"
AND `name` <> "Acolyte\'s Shoes"
AND `name` <> "Apprentice\'s Boots"
AND `name` <> "Apprentice\'s Pants"
AND `name` <> "Apprentice\'s Robe"
AND `name` <> "Apprentice\'s Shirt"
AND `name` <> "Neophyte\'s Boots"
AND `name` <> "Neophyte\'s Pants"
AND `name` <> "Neophyte\'s Robe"
AND `name` <> "Neophyte\'s Shirt"
AND `name` <> "Recruit\'s Boots"
AND `name` <> "Recruit\'s Pants"
AND `name` <> "Recruit\'s Robe"
AND `name` <> "Recruit\'s Shirt"
AND `name` <> "Squire\'s Boots"
AND `name` <> "Squire\'s Pants
AND `name` <> "Squire\'s Pants"
AND `name` <> "Squire\'s Shirt"
AND `name` <> "Darnassian Bleu"
AND `name` <> "Forest Mushroom Cap"
AND `name` <> "Guild Tabard"
AND `name` <> "Refreshing Spring Water"
AND `name` <> "Tough Hunk of Bread"
AND `name` <> "Tough Jerky"
AND `name` <> "Battleworn Hammer"
AND `name` <> "Bent Staff"
AND `name` <> "Worn Battleaxe"
AND `name` <> "Worn Dagger"
AND `name` <> "Worn Mace"
AND `name` <> "Worn Shortsword"
AND `name` <> "Worn Wooden Shield"
AND `name` <> "Azure Watch Gift Voucher"
AND `name` <> "Bloodhoof Village Gift Voucher"
AND `name` <> "Brill Gift Voucher"
AND `name` <> "Dolanaar Gift Voucher"
AND `name` <> "Falconwing Square Gift Voucher"
AND `name` <> "Goldshire Gift Voucher"
AND `name` <> "Kharanos Gift Voucher"
AND `name` <> "Razor Hill Gift Voucher"
AND `name` <> "Diablo Stone"
AND `name` <> "Panda Collar"
AND `name` <> "Zergling Leash"
AND `name` <> "Netherwhelp\'s Collar"
AND `name` <> "Lurky\'s Egg";
