DELETE FROM `protoitem` WHERE
 `name` <> "Hearthstone"
 AND `name` <> "Acolyte\'s Shirt"
 AND `name` <> "Acolyte\'s Shoes"
 AND `name` <> "Apprentice\'s Boots"
 AND `name` <> "Apprentice\'s Shirt"
 AND `name` <> "Neophyte\'s Boots"
 AND `name` <> "Neophyte\'s Shirt"
 AND `name` <> "Recruit\'s Boots"
 AND `name` <> "Recruit\'s Shirt"
 AND `name` <> "Squire\'s Boots"
 AND `name` <> "Squire\'s Shirt"
 AND `name` <> "Acolyte\'s Pants"
 AND `name` <> "Acolyte\'s Robe"
 AND `name` <> "Apprentice\'s Pants"
 AND `name` <> "Apprentice\'s Robe"
 AND `name` <> "Neophyte\'s Pants"
 AND `name` <> "Neophyte\'s Robe"
 AND `name` <> "Recruit\'s Pants"
 AND `name` <> "Recruit\'s Robe"
 AND `name` <> "Squire\'s Pants"
 AND `name` <> "Tough Jerky"
 AND `name` <> "Guild Tabard"
 AND `name` <> "Refreshing Spring Water"
 AND `name` <> "Darnassian Bleu"
 AND `name` <> "Forest Mushroom Cap"
 AND `name` <> "Tough Hunk of Bread";
