#!/bin/sh

# Dump structure and data for realms
mysqldump \
    -umangos2 \
    -hlocalhost \
    -pmangos2 -Q \
    --add-drop-table mangos2-authserver realms > authserver/realms.sql

# Dump structure and data for accounts
mysqldump \
    -umangos2 \
    -hlocalhost \
    -pmangos2 -Q \
    --add-drop-table mangos2-authserver accounts > authserver/accounts.sql

# Dump structure for character per account count
mysqldump \
    -umangos2 \
    -hlocalhost \
    -pmangos2 -Q \
    --add-drop-table \
    --no-data mangos2-authserver accountchars > authserver/accountchars.sql

mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table mangos2-worlddata access_levels > worlddata/access_levels.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table --no-data mangos2-worlddata characters > worlddata/characters.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table --no-data mangos2-worlddata guid_pool > worlddata/guid_pool.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table mangos2-worlddata protochar > worlddata/protochar.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table mangos2-worlddata protoitem > worlddata/protoitem.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table --no-data mangos2-worlddata items > worlddata/items.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table --no-data mangos2-worlddata quest_status > worlddata/quest_status.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table --no-data mangos2-worlddata inventory > worlddata/inventory.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table --no-data mangos2-worlddata char_spells > worlddata/char_spells.sql
mysqldump -umangos2 -hlocalhost -pmangos2 -Q --add-drop-table --no-data mangos2-worlddata mail > worlddata/mail.sql

# Replace VALUES ( by VALUES\n(
find ./ -name '*.sql' -type f -exec perl -pi -e 's/VALUES \(/VALUES\n\(/g' {} \; -print

# Replace huge insert by multi-line inserts
find ./ -name '*.sql' -type f -exec perl -pi -e 's/\),\(/\),\n\(/g' {} \; -print
